[nlp]
token = "RNU4R7ODQSJOAQQUBFDUIM7LTCYB45XH"

[server]
ip = "0.0.0.0"
port = 27015

[common]
city = "Санкт-Петербург"
categories = ["Газ", "Отопление", "Электричество", "Канализация"]
categoriesGiving = ["газу", "отоплению", "электричеству", "канализации"]

[strings]
chooseCategory = "Пожалуйста, выберите категорию из списка:"
dontUnderstand = "Прошу прощения, я не понимаю Вас."
categoryNotFound = "Пожалуйста, выберите тип проблемы из списка:"
badTelephoneNumber = "Пожалуйста, введите телефонный номер в виде: +7-XXX-XXX-XX-XX"
badAddress = "Пожалуйста, укажите корректный адрес в городе %v"
telephoneRequest = "Пожалуйста, введите Ваш номер телефона для связи"
addressRequest = "Пожалуйста, введите Ваш адрес"
checkRequest = "Спасибо за обращение. Пожалуйста, подтвердите правильность введённой Вами информации:"
finalMessage = "%v, Ваш запрос будет обработан в ближайшее время нашими специалистами по %v, ожидайте, с вами свяжутся по телефону %v"
enterAddress = "Пожалуйста, введите Ваш адрес (например, ул. Большая Морская д.5 кв.14)"
enterPhoneNumber = "Пожалуйста, введите Ваш номер телефона для связи"
enterName = "Как к Вам можно обращаться?"
